version: 2.1
 
jobs:
  terraform:
    docker:
    - image: hashicorp/terraform:1.6.5
 
    #working_directory: ~/Terraform-Test/TF-Modules/EC2
 
    steps:
    - checkout
 
    - run:
        name: Terraform Init
        command: terraform init
        path: environment/dev/
 
    - run:
        name: Terraform plan
        command: terraform plan
        path: environment/dev/
 
    - run:
        name: Terraform Apply
        command: terraform apply -auto-approve
        path: environment/dev/
 
workflows:
  version: 2
  main:
    jobs:
    - terraform:
        filters:
          branches:
            only:
            - main
