version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:latest

#    working_directory: ~/terrafarm-test

    steps:
      - checkout

      - run:
          name: Terraform Init
          command: terraform init
          path: environment/dev/
          
      - run:
          name: Terraform Plan
          command: terraform plan

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  build:
    jobs:
      - terraform
