version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:0.15.0  # Use the specific version you want

    working_directory: ~/terrafarm-test

    steps:
      - checkout

      - run:
          name: Change to Terraform Directory
          command: cd environment/dev/

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  build:
    jobs:
      - terraform
