version: 2.1

jobs:
  init-terraform-dev:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform Init - Dev
          command: |
            cd ./environment/dev/
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=us-east-1
            terraform init \
              -backend-config="bucket=terrastatekade" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="region=us-east-1" \
              -backend-config="encrypt=true"

  tf_plan_dev:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Terraform Plan - Dev
          command: |
            cd ./environment/dev/
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=us-east-1
            terraform plan -out=/tmp/plan.out
      - persist_to_workspace:
          root: /tmp
          paths:
            - plan.out

  init-terraform-test:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform Init - Test
          command: |
            cd ./environment/test/
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TEST
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TEST
            export AWS_DEFAULT_REGION=us-east-1
            terraform init \
              -backend-config="bucket=terrastatekade" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="region=us-east-1" \
              -backend-config="encrypt=true"

  tf_plan_test:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Terraform Plan - Test
          command: |
            cd ./environment/test/
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TEST
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TEST
            export AWS_DEFAULT_REGION=us-east-1
            terraform plan -out=/tmp/plan.out
      - persist_to_workspace:
          root: /tmp
          paths:
            - plan.out

workflows:
  version: 2
  main:
    jobs:
      - init-terraform-dev
      - tf_plan_dev:
          requires:
            - init-terraform-dev
      - init-terraform-test:
          requires:
            - tf_plan_dev
      - tf_plan_test:
          requires:
            - init-terraform-test
