version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
      - terraform/apply:
          checkout: true
          context: terraform
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
