version: 2.1

parameters:
  environment:
    description: "Deployed environment folder name"
    type: string
    default: ""
  environment_uppercase:
    description: "Deployed environment folder name - uppercase"
    type: string
    default: ""

jobs:
  init-terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: |
          cd ./environment/<< parameters.environment >>/
          terraform init \
            -backend-config="bucket=terrastatekade" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"

  tf_plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: |
          cd ./environment/<< parameters.environment >>/
          terraform plan -out=/tmp/plan.out
      - persist_to_workspace:
          root: /tmp
          paths:
            - plan.out

workflows:
  version: 2
  main:
    jobs:
      - init-terraform:
          environment: "dev"
          environment_uppercase: "DEV"

      - init-terraform:
          environment: "test"
          environment_uppercase: "TEST"
          requires:
            - init-terraform

      - tf_plan:
          environment: "dev"
          environment_uppercase: "DEV"
          requires:
            - init-terraform

      - tf_plan:
          environment: "test"
          environment_uppercase: "TEST"
          requires:
            - init-terraform
